### ISSUE TITLE
「或許」原始的 JSON 檔會更好用？

### ISSUE THREAD

**Issue by bobchao** [infax/COSCUP-2017-Submissions#2]
參考一下 https://coscup.org/2017-assets/json/submissions.json

**Comment by infax** [comment]
是用這份呀~ 每次開頁面會重抓哦，所以官方有變換資料也會跟著變
只是key值是index 反而不好排資料，所以將資料重排過把day跟room都變型key上了

**Comment by bobchao** [comment]
喔喔沒有注意到，感謝，隨便看以為你是 parse 頁面產出的 node XD.. （現在認真想想這樣實在更麻煩，我想錯了）
